"""
kp6_holes.py — 6-band k.p (Luttinger-Kohn-Bir-Pikus, Gamma8+Gamma7) model of
the Si FinFET hole channel: the first theory upgrade flagged in lk_holes.py.

Question answered: silicon's split-off gap Delta_so = 44 meV is comparable to
the fin confinement energies (tens of meV at 7-16 nm), so the 4-band model's
underprediction of the wire-axis g-factor (g_x in [0.4, 1.1] vs measured
1.9-2.3, Geyer 2024) may be a split-off-coupling artifact. This module builds
the full 6x6 model with the same extraction conventions as lk_holes.py so the
two are exactly swappable, and quantifies how Delta_so moves (m*, alpha,
g-tensor).

CONVENTIONS (referee checklist)
-------------------------------
* Hole picture, energies POSITIVE into the valence band, exactly as
  lk_holes.py: the lowest eigenvalues of H are the topmost valence states.
  Consequently the split-off (Gamma7) band sits at +Delta_so = +44 meV in our
  spectra (equivalently -44 meV in the electron picture).
* Basis: |J,mJ> = |3/2,+3/2>, |3/2,+1/2>, |3/2,-1/2>, |3/2,-3/2>,
  |1/2,+1/2>, |1/2,-1/2>, built from |X,Y,Z> x |up,down> with Condon-Shortley
  Clebsch-Gordan phases and e_{+1} = -(x+iy)/sqrt2. With these phases the
  Gamma8 block of the total angular momentum J = L + S reproduces the
  spin-3/2 matrices JX, JY, JZ of lk_holes.py to machine precision (asserted
  at import), so all 4-band and 6-band expectation values are directly
  comparable.
* Kinetic term: the p-multiplet orbital Hamiltonian H_ab = [L ka^2
  + M (kb^2+kc^2)] delta_ab + N {ka,kb} (a,b in x,y,z; {,} symmetrized), with
  hole-picture L = (hbar^2/2m0)(g1+4 g2), M = (hbar^2/2m0)(g1-2 g2),
  N = (hbar^2/2m0) 6 g3, rotated to the |J,mJ> basis. Its Gamma8 projection
  is EXACTLY the 4-band LK Hamiltonian of lk_holes.py (full cubic anisotropy,
  no axial approximation; asserted at import); its Gamma7 projection is
  (hbar^2/2m0) g1 k^2 (+Delta_so); the Gamma8-Gamma7 coupling blocks are the
  standard Chao-Chuang / Winkler P,Q,R,S combinations — all three follow from
  the one L,M,N matrix, so the coupling phases are consistent by
  construction. Validation: the bulk 6x6 reproduces the closed-form
  HH/(LH-SO) dispersions along [001] and [111] (coupling elements
  2*sqrt2*g2*k~^2 and 2*sqrt2*g3*k~^2) to machine precision.
* No double counting: the Luttinger gammas are Gamma8 band-edge parameters
  generated by REMOTE bands (Gamma6c etc.); the explicit Gamma8-Gamma7
  coupling added here is internal to the p multiplet and contributes to
  Gamma8 energies only at order k^4/Delta_so (nothing at the band edge), so
  using the same Lawaetz gammas (4.285, 0.339, 1.446) in the 6-band model is
  the standard prescription (Chao-Chuang 1992; Winkler 2003) and involves no
  double counting.
* Zeeman: written as H_Z = mu_B (g_L^h B.L + g_s^h B.S) within the
  6-dim multiplet (hole picture), with g_s^h = -2 (bare spin, sign flipped by
  the hole convention) and g_L^h = 3 kappa + 1 fixed by requiring the Gamma8
  projection to equal lk_holes' +2 kappa mu_B B.J (projection theorem:
  P8 L P8 = (2/3) J, P8 S P8 = (1/3) J). This reproduces Luttinger's
  kappa = -2/3 atomic limit (g_L^h = -1, pure-p multiplet) and implies the
  Gamma7 block H_Z(Gamma7) = 2(2 kappa + 1) mu_B B.sigma/2 in our hole
  convention (electron-picture Gamma7 g-factor -2(2 kappa + 1), the Winkler
  "-2(kappa + ...)" form), plus the Gamma8-Gamma7 Zeeman coupling block, both
  generated automatically by the same L,S decomposition (asserted at import).
  The cubic q J^3 term is neglected (q ~ 0.01 in Si), as in lk_holes.py.
* Orbital magnetic field: vector-potential (Peierls) substitution
  k -> k + eA/hbar with A = (B_y z - B_z y, 0, B_x y) inside the transverse
  momentum operators, with the identical operator formulas of
  lk_holes.build_fin_H, so orbital and bare Zeeman effects enter the 6-band
  g-tensor on exactly the same footing as in the 4-band model.
* Geometry: hard-wall rectangular fin (y = width, z = vertical), wire along
  x = [100] (crystal axes), vertical gate field U = +e E_z z (identical sign
  to lk_holes).

TWO DISCRETIZATIONS (why both exist)
------------------------------------
* basis="fd": symmetrized central finite differences on the interior grid,
  line-for-line the operators of lk_holes.build_fin_H. Used for validation
  (c): with Delta_so -> infinity the 6-band model must reproduce
  lk_holes.extract at the same grid — it does to < 0.01 %, which pins every
  basis/coupling/Zeeman convention against the 4-band code.
* basis="dst" (production): hard-wall sine (Galerkin) basis: -d2/dx2 is
  exact and diagonal, -i d/dx and the position operator use the analytic
  sine-basis matrix elements. Same continuum Hamiltonian, near-spectral
  convergence. This is needed because at the physical Delta_so = 44 meV the
  Gamma8-Gamma7 mixing is strong (confinement energies ~ Delta_so) and
  amplifies the O(d^2) FD error: the FD extraction outputs still drift 6-9 %
  between an 11x13 and a 15x17 grid, never reaching the < 3 % convergence
  gate at affordable sizes, while the sine basis passes it at 11x13 modes.
  Validation A cross-checks the two: the FD results on refining grids
  (11x13 -> 15x17 -> 19x21) must approach the converged sine-basis values.

extract6(Ez, ...) returns (m*/m0, alpha_eVA, gx, gy, gz, nso) for the lowest
Kramers doublet with the identical recipes of lk_holes.extract (kx curvature
at k1 = 2e7/m, linear-in-kx splitting for alpha, B = 0.05 T field derivative
of the doublet splitting for g, <J> of the kx-split doublet for the SOC
axis), so downstream code can swap the models.

Checkpointing: results cached per-section in output/data/kp6.json; reruns
skip finished sections (--force to redo). Key numbers go to the repo ledger
via run_analysis.save_numbers("kp6", ...).

Sections (python kp6_holes.py --sec A|B|C|D|all):
  A  validation gauntlet (bulk edges, [100] HH mass, closed-form LH-SO
     branches, Delta_so->inf vs lk_holes, FD->sine cross-check, Kramers,
     hermiticity, basis-size convergence) — must pass before B-D run;
  B  extract6 vs Ez in {2,5,10,15,20,30,40,50} MV/m at 10x12 nm (fig10 table);
  C  seven-geometry bracket (fig10 g_bracket list) — 6-band g_x range;
  D  Delta_so sensitivity at the production point: 44 / 100 / 300 / 1e6 meV.
"""

import argparse
import json
import os
import sys
import time

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
try:  # sandbox without scipy/matplotlib: use the repo's compat shim
    import scipy.sparse.linalg  # noqa: F401
    import matplotlib.pyplot    # noqa: F401
except Exception:
    sys.path.insert(0, os.path.join(_HERE, "compat"))

import lk_holes
from lk_holes import (HBAR, M0, QE, MU_B_J, G1, G2, G3, KAPPA,
                      JX, JY, JZ, I4, _sym, _d1, _d2)

MEV_J = QE * 1e-3
DSO_MEV = 44.0                      # Si split-off gap
DATA = os.path.join(_HERE, "output", "data")
os.makedirs(DATA, exist_ok=True)
CKPT = os.path.join(DATA, "kp6.json")

PROD = dict(Wy=10e-9, Wz=12e-9, ny=11, nz=13, Ez=1e7)   # production point

# fig10 g_bracket seven-geometry list: (Wy_nm, Wz_nm, Ez_MV/m); mode rule
# n = W_nm + 1 keeps the production resolution per nm.
GEOMS = {
    "base_10x12_Ez10":  (10, 12, 10),
    "narrow_7x14_Ez10": (7, 14, 10),
    "wide_16x8_Ez10":   (16, 8, 10),
    "square_9x9_Ez10":  (9, 9, 10),
    "base_10x12_Ez3":   (10, 12, 3),
    "base_10x12_Ez30":  (10, 12, 30),
    "tall_8x16_Ez10":   (8, 16, 10),
}


def save_numbers(tag, d):
    """run_analysis.save_numbers if importable, else same merge locally."""
    try:
        import run_analysis
        run_analysis.save_numbers(tag, d)
        return
    except Exception:
        pass
    path = os.path.join(DATA, "key_numbers.json")
    allnum = {}
    if os.path.exists(path):
        with open(path) as f:
            allnum = json.load(f)
    allnum[tag] = {**allnum.get(tag, {}), **d}
    with open(path, "w") as f:
        json.dump(allnum, f, indent=2)
    print(f"[{tag}] " + json.dumps(d))


# --------------------------------------------------------------- basis setup
def _ket(ml, sdn):
    """|1,ml>|spin> in the (X up, Y up, Z up, X dn, Y dn, Z dn) basis."""
    e = {+1: np.array([-1.0, -1.0j, 0.0]) / np.sqrt(2.0),
         0:  np.array([0.0, 0.0, 1.0], dtype=complex),
         -1: np.array([1.0, -1.0j, 0.0]) / np.sqrt(2.0)}[ml]
    v = np.zeros(6, complex)
    v[3 * sdn:3 * sdn + 3] = e
    return v


_r13, _r23 = np.sqrt(1.0 / 3.0), np.sqrt(2.0 / 3.0)
U6 = np.column_stack([
    _ket(+1, 0),                                  # |3/2,+3/2>
    _r13 * _ket(+1, 1) + _r23 * _ket(0, 0),       # |3/2,+1/2>
    _r23 * _ket(0, 1) + _r13 * _ket(-1, 0),       # |3/2,-1/2>
    _ket(-1, 1),                                  # |3/2,-3/2>
    _r23 * _ket(+1, 1) - _r13 * _ket(0, 0),       # |1/2,+1/2>
    _r13 * _ket(0, 1) - _r23 * _ket(-1, 0),       # |1/2,-1/2>
])

LX3 = np.array([[0, 0, 0], [0, 0, -1j], [0, 1j, 0]], complex)
LY3 = np.array([[0, 0, 1j], [0, 0, 0], [-1j, 0, 0]], complex)
LZ3 = np.array([[0, -1j, 0], [1j, 0, 0], [0, 0, 0]], complex)
SX2 = 0.5 * np.array([[0, 1], [1, 0]], complex)
SY2 = 0.5 * np.array([[0, -1j], [1j, 0]], complex)
SZ2 = 0.5 * np.array([[1, 0], [0, -1]], complex)
I2, I3 = np.eye(2, dtype=complex), np.eye(3, dtype=complex)
I6 = np.eye(6, dtype=complex)
P7 = np.diag([0., 0., 0., 0., 1., 1.]).astype(complex)

Lj = [U6.conj().T @ np.kron(I2, La) @ U6 for La in (LX3, LY3, LZ3)]
Sj = [U6.conj().T @ np.kron(Sa, I3) @ U6 for Sa in (SX2, SY2, SZ2)]
J6 = [l + s for l, s in zip(Lj, Sj)]


def _E3(a, b):
    m = np.zeros((3, 3), complex)
    m[a, b] = 1.0
    return m


CAB = [[U6.conj().T @ np.kron(I2, _E3(a, b)) @ U6 for b in range(3)]
       for a in range(3)]

# Zeeman decomposition (see docstring): hole picture
GS_H = -2.0
GL_H = 3.0 * KAPPA + 1.0


def _zeeman6(B):
    return MU_B_J * sum(Bi * (GL_H * Li + GS_H * Si)
                        for Bi, Li, Si in zip(B, Lj, Sj))


# import-time consistency asserts (basis phases vs lk_holes)
def _basis_selfcheck():
    assert np.abs(U6.conj().T @ U6 - I6).max() < 1e-14, "U6 not unitary"
    for Jfull, Jlk in zip(J6, (JX, JY, JZ)):
        assert np.abs(Jfull[:4, :4] - Jlk).max() < 1e-14, "Gamma8 J mismatch"
        assert np.abs(Jfull[:4, 4:]).max() < 1e-14, "J couples G8-G7"
    for Jfull, S2 in zip(J6, (SX2, SY2, SZ2)):
        assert np.abs(Jfull[4:, 4:] - S2).max() < 1e-14, "Gamma7 J mismatch"
    for Li, Si, Jlk, S2 in zip(Lj, Sj, (JX, JY, JZ), (SX2, SY2, SZ2)):
        Z = GL_H * Li + GS_H * Si
        assert np.abs(Z[:4, :4] - 2 * KAPPA * Jlk).max() < 1e-13, \
            "Gamma8 Zeeman != 2 kappa J"
        assert np.abs(Z[4:, 4:] - 2 * (2 * KAPPA + 1) * S2).max() < 1e-13, \
            "Gamma7 Zeeman != 2(2kappa+1) sigma/2"


_basis_selfcheck()


# --------------------------------------------------------------- bulk model
def _LMN():
    pref = HBAR**2 / (2 * M0)
    return pref * (G1 + 4 * G2), pref * (G1 - 2 * G2), pref * 6 * G3


def bulk_H6(k, Dso_meV=DSO_MEV):
    """Bulk 6x6 at numeric k = (kx,ky,kz), hole picture (Joules)."""
    Lp, Mp, Np = _LMN()
    kx, ky, kz = k
    Hor = np.array([
        [Lp * kx * kx + Mp * (ky * ky + kz * kz), Np * kx * ky, Np * kx * kz],
        [Np * kx * ky, Lp * ky * ky + Mp * (kx * kx + kz * kz), Np * ky * kz],
        [Np * kx * kz, Np * ky * kz, Lp * kz * kz + Mp * (kx * kx + ky * ky)],
    ], dtype=complex)
    return (U6.conj().T @ np.kron(I2, Hor) @ U6
            + Dso_meV * MEV_J * P7)


def _lk_bulk4(kx, ky, kz):
    """lk_holes-convention bulk 4x4 (for the Gamma8-corner identity check)."""
    pref = HBAR**2 / (2 * M0)
    k2 = kx * kx + ky * ky + kz * kz
    return pref * ((G1 + 2.5 * G2) * k2 * I4
                   - 2 * G2 * (kx * kx * (JX @ JX) + ky * ky * (JY @ JY)
                               + kz * kz * (JZ @ JZ))
                   - 4 * G3 * (kx * ky * _sym(JX, JY) + ky * kz * _sym(JY, JZ)
                               + kz * kx * _sym(JZ, JX)))


# ----------------------------------------------------------------- fin model
def _dst_ops(n, W):
    """Hard-wall sine-basis 1D operators (modes m = 1..n on [0, W]):
    exact -d2/dx2 (diagonal), analytic <m|-i d/dx|n> and centered position."""
    m = np.arange(1, n + 1)
    K2 = np.diag((m * np.pi / W) ** 2)
    a = m[:, None].astype(float)
    b = m[None, :].astype(float)
    odd = (m[:, None] + m[None, :]) % 2 == 1
    with np.errstate(divide="ignore", invalid="ignore"):
        D1 = np.where(odd, 4.0 * a * b / (W * (a * a - b * b)), 0.0)
        X = np.where(odd, -2.0 * W / np.pi**2
                     * (1.0 / (a - b) ** 2 - 1.0 / (a + b) ** 2), 0.0)
    np.fill_diagonal(D1, 0.0)
    np.fill_diagonal(X, 0.0)          # centered: <m|y - W/2|m> = 0
    return K2, D1, X


def build_fin_H6(kx, Ez_Vm=0.0, B=(0.0, 0.0, 0.0),
                 Wy=10e-9, Wz=12e-9, ny=11, nz=13, Dso_meV=DSO_MEV,
                 basis="dst"):
    """Dense 6*ny*nz Hamiltonian of the fin cross-section at wire momentum
    kx. basis="fd": lk_holes-identical grid operators (ny x nz interior
    points); basis="dst": hard-wall sine basis (ny x nz modes). Field signs
    and Peierls substitution identical to lk_holes.build_fin_H. Energies in
    Joules (hole picture, positive)."""
    Iy, Iz = np.eye(ny), np.eye(nz)
    Ig = np.eye(ny * nz)
    Bx, By, Bz = B
    c = QE / HBAR
    if basis == "fd":
        dy, dz = Wy / (ny + 1), Wz / (nz + 1)
        y = (np.arange(ny) + 1) * dy - Wy / 2
        z = (np.arange(nz) + 1) * dz - Wz / 2
        Yd = np.kron(np.diag(y), Iz)
        Zd = np.kron(Iy, np.diag(z))
        KYb = -1j * np.kron(_d1(ny, dy), Iz)
        KZb = -1j * np.kron(Iy, _d1(nz, dz))
        KY2 = -np.kron(_d2(ny, dy), Iz) + 0j
        KZ2b = -np.kron(Iy, _d2(nz, dz)) + 0j
    elif basis == "dst":
        K2y, D1y, Xy = _dst_ops(ny, Wy)
        K2z, D1z, Xz = _dst_ops(nz, Wz)
        Yd = np.kron(Xy, Iz)
        Zd = np.kron(Iy, Xz)
        KYb = -1j * np.kron(D1y, Iz)
        KZb = -1j * np.kron(Iy, D1z)
        KY2 = np.kron(K2y, Iz) + 0j
        KZ2b = np.kron(Iy, K2z) + 0j
    else:
        raise ValueError(f"unknown basis {basis!r}")
    KX = kx * Ig + c * (By * Zd - Bz * Yd)
    KY = KYb
    KZ = KZb + c * Bx * Yd
    KX2 = KX @ KX
    KZ2 = KZ2b + (2 * c * Bx * _sym(KZb, Yd) + (c * Bx) ** 2 * (Yd @ Yd)
                  if Bx else 0)
    Lp, Mp, Np = _LMN()
    Op = [[None] * 3 for _ in range(3)]
    Op[0][0] = Lp * KX2 + Mp * (KY2 + KZ2)
    Op[1][1] = Lp * KY2 + Mp * (KX2 + KZ2)
    Op[2][2] = Lp * KZ2 + Mp * (KX2 + KY2)
    Op[0][1] = Op[1][0] = Np * _sym(KX, KY)
    Op[1][2] = Op[2][1] = Np * _sym(KY, KZ)
    Op[0][2] = Op[2][0] = Np * _sym(KZ, KX)
    n6 = 6 * ny * nz
    H = np.zeros((n6, n6), complex)
    for a in range(3):
        for b in range(3):
            H += np.kron(Op[a][b], CAB[a][b])
    H += np.kron(QE * Ez_Vm * Zd, I6)
    H += Dso_meV * MEV_J * np.kron(Ig, P7)
    if any(B):
        H += np.kron(Ig, _zeeman6(B))
    return H


def extract6(Ez_Vm, Wy=10e-9, Wz=12e-9, ny=11, nz=13,
             k1=2e7, Btest=0.05, Dso_meV=DSO_MEV, basis="dst"):
    """(m*/m0, alpha_eVA, gx, gy, gz, nso) for the lowest Kramers doublet.
    Identical extraction recipes to lk_holes.extract."""
    kw = dict(Wy=Wy, Wz=Wz, ny=ny, nz=nz, Dso_meV=Dso_meV, basis=basis)
    e0 = np.linalg.eigvalsh(build_fin_H6(0.0, Ez_Vm, (0, 0, 0), **kw))[:2]
    ek = np.linalg.eigvalsh(build_fin_H6(k1, Ez_Vm, (0, 0, 0), **kw))[:2]
    alpha_Jm = (ek[1] - ek[0]) / (2 * k1)
    dE = ek.mean() - e0.mean()
    mstar = HBAR**2 * k1**2 / (2 * dE) / M0 if dE > 0 else np.nan
    gs = []
    for ax in range(3):
        Bv = [0.0, 0.0, 0.0]
        Bv[ax] = Btest
        eb = np.linalg.eigvalsh(build_fin_H6(0.0, Ez_Vm, tuple(Bv), **kw))[:2]
        gs.append((eb[1] - eb[0]) / (MU_B_J * Btest))
    w, v = np.linalg.eigh(build_fin_H6(k1, Ez_Vm, (0, 0, 0), **kw))
    Ng = v.shape[0] // 6
    nso = []
    for Jm in J6:
        Op = np.kron(np.eye(Ng), Jm)
        nso.append(float(np.real(v[:, 0].conj() @ Op @ v[:, 0]
                                 - v[:, 1].conj() @ Op @ v[:, 1])))
    nso = np.array(nso)
    nrm = np.linalg.norm(nso)
    nso = nso / nrm if nrm > 1e-9 else nso
    return (float(mstar), float(alpha_Jm / QE / 1e-10),
            float(gs[0]), float(gs[1]), float(gs[2]), nso.tolist())


def _lso_nm(m, al):
    return HBAR**2 / (m * M0 * al * QE * 1e-10) * 1e9 if al > 1e-6 else np.inf


# ------------------------------------------------------------- checkpointing
def _load():
    if os.path.exists(CKPT):
        with open(CKPT) as f:
            return json.load(f)
    return {}


def _save(d):
    with open(CKPT, "w") as f:
        json.dump(d, f, indent=2)


def _pct(a, b):
    return 100.0 * abs(a - b) / max(abs(b), 1e-30)


def _row(res):
    m, al, gx, gy, gz, nso = res
    return dict(mstar=round(m, 4), alpha_eVA=round(al, 4),
                gx=round(gx, 4), gy=round(gy, 4), gz=round(gz, 4),
                lso_nm=round(_lso_nm(m, al), 1),
                nso=[round(x, 3) for x in nso])


NAMES = ["mstar", "alpha_eVA", "gx", "gy", "gz"]


# ------------------------------------------------------------------ sections
def sec_A():
    """Validation gauntlet a-e. All must pass before physics sections."""
    t0 = time.time()
    out, ok = {}, True

    # (a) bulk band edges at k = 0
    ev = np.linalg.eigvalsh(bulk_H6((0.0, 0.0, 0.0)))
    g8 = np.abs(ev[:4]).max() / MEV_J
    g7 = ev[4:] / MEV_J
    pa = g8 < 1e-12 and np.abs(g7 - DSO_MEV).max() < 1e-10
    out["a_bulk_k0"] = dict(
        gamma8_max_abs_meV=float(g8),
        gamma7_meV=[float(x) for x in g7],
        note="hole picture: Gamma7 at +44 meV == -44 meV electron picture",
        passed=bool(pa))
    ok &= pa

    # (b) bulk [100] HH mass + closed-form HH/(LH-SO) branches [001], [111]
    kmag = 2.3e8
    kt = HBAR**2 * kmag**2 / (2 * M0)
    dev = 0.0
    for axis, gg in (((0, 0, 1), G2), ((1, 1, 1), G3)):
        n = np.array(axis, float)
        n /= np.linalg.norm(n)
        ev = np.linalg.eigvalsh(bulk_H6(tuple(n * kmag)))
        hh = (G1 - 2 * gg) * kt
        m22 = np.array([[(G1 + 2 * gg) * kt, 2 * np.sqrt(2) * gg * kt],
                        [2 * np.sqrt(2) * gg * kt,
                         G1 * kt + DSO_MEV * MEV_J]])
        e2 = np.linalg.eigvalsh(m22)
        expect = np.sort([hh, hh, e2[0], e2[0], e2[1], e2[1]])
        dev = max(dev, float(np.abs((ev - expect) / expect).max()))
    m_hh = 1.0 / (G1 - 2 * G2)
    pb = dev < 1e-10
    out["b_bulk_branches"] = dict(
        m_hh_100=float(round(m_hh, 4)), expect=0.2773,
        max_rel_dev_vs_closed_form_001_111=dev,
        passed=bool(pb))
    ok &= pb

    # internal basis/corner identities (random k, fixed seed)
    rng = np.random.default_rng(7)
    crn = 0.0
    for _ in range(5):
        kv = rng.uniform(-3e8, 3e8, 3)
        H6b = bulk_H6(tuple(kv))
        scale = np.abs(H6b).max()
        crn = max(crn, np.abs(H6b[:4, :4] - _lk_bulk4(*kv)).max() / scale)
        g7blk = H6b[4:, 4:] - DSO_MEV * MEV_J * np.eye(2)
        e7 = HBAR**2 / (2 * M0) * G1 * (kv @ kv)
        crn = max(crn, np.abs(g7blk - e7 * np.eye(2)).max() / scale)
    pi = crn < 1e-12
    out["internal_corner_identities"] = dict(max_rel_dev=float(crn),
                                             passed=bool(pi))
    ok &= pi

    # (c) Delta_so -> infinity, lk-identical FD operators, same grid:
    # must reproduce lk_holes.extract (pins every convention choice)
    six = extract6(PROD["Ez"], Dso_meV=1e6, basis="fd")
    four = lk_holes.extract(PROD["Ez"])
    diffs = {n: round(_pct(six[i], four[i]), 4) for i, n in enumerate(NAMES)}
    pc = max(diffs.values()) < 2.0
    out["c_dso_inf_limit_fd"] = dict(
        six_band={n: round(six[i], 4) for i, n in enumerate(NAMES)},
        four_band={n: round(four[i], 4) for i, n in enumerate(NAMES)},
        pct_diff=diffs, passed=bool(pc))
    ok &= pc

    # (c2) discretization cross-check at the physical Delta_so: the FD
    # results on refining grids must approach the sine-basis values
    dst = extract6(PROD["Ez"])                      # production: dst 11x13
    fd_seq = {}
    for g in ((11, 13), (15, 17), (19, 21)):
        fd_seq[f"{g[0]}x{g[1]}"] = extract6(PROD["Ez"], ny=g[0], nz=g[1],
                                            basis="fd")
        print(f"  A/c2: fd {g} done t={time.time()-t0:.0f}s", flush=True)
    d_first = {n: _pct(fd_seq["11x13"][i], dst[i])
               for i, n in enumerate(NAMES)}
    d_last = {n: _pct(fd_seq["19x21"][i], dst[i])
              for i, n in enumerate(NAMES)}
    pc2 = all(d_last[n] < d_first[n] for n in NAMES)
    out["c2_fd_to_dst_crosscheck"] = dict(
        dst_11x13={n: round(dst[i], 4) for i, n in enumerate(NAMES)},
        fd_sequence={g: {n: round(r[i], 4) for i, n in enumerate(NAMES)}
                     for g, r in fd_seq.items()},
        fd_minus_dst_pct_coarse={n: round(v, 2) for n, v in d_first.items()},
        fd_minus_dst_pct_fine={n: round(v, 2) for n, v in d_last.items()},
        passed=bool(pc2))
    ok &= pc2

    # (d) Kramers degeneracy at B = 0, kx = 0, any Ez (production basis)
    worst = 0.0
    for Ez in (0.0, PROD["Ez"], 2.5e7):
        ev = np.linalg.eigvalsh(build_fin_H6(0.0, Ez))
        for i in range(30):
            split = ev[2 * i + 1] - ev[2 * i]
            spacing = ev[2 * i + 2] - ev[2 * i]
            if spacing > 0:
                worst = max(worst, split / spacing)
    pd = worst < 1e-10
    out["d_kramers"] = dict(max_split_over_spacing=float(worst),
                            passed=bool(pd))
    ok &= pd

    # (e) hermiticity + basis-size convergence (production basis)
    herm = 0.0
    for bas in ("fd", "dst"):
        H = build_fin_H6(2e7, 3e7, (0.05, 0.05, 0.05), basis=bas)
        herm = max(herm, float(np.abs(H - H.conj().T).max()))
    fine = extract6(PROD["Ez"], ny=PROD["ny"] + 4, nz=PROD["nz"] + 4)
    conv = {n: round(_pct(dst[i], fine[i]), 3) for i, n in enumerate(NAMES)}
    pe = herm < 1e-25 and max(conv.values()) < 3.0
    out["e_herm_convergence"] = dict(
        max_nonhermiticity_J=herm,
        dst_change_pct_11x13_vs_15x17_modes=conv, passed=bool(pe))
    ok &= pe

    out["all_passed"] = bool(ok)
    out["runtime_s"] = round(time.time() - t0, 1)
    return out


def sec_B():
    """6-band extract6 vs Ez at the production cross-section (fig10 table)."""
    t0 = time.time()
    rows = {}
    for EzM in (2, 5, 10, 15, 20, 30, 40, 50):
        res = extract6(EzM * 1e6)
        rows[f"Ez{EzM}"] = _row(res)
        print(f"  B: Ez={EzM} MV/m done t={time.time()-t0:.0f}s", flush=True)
    gx = [r["gx"] for r in rows.values()]
    al = [r["alpha_eVA"] for r in rows.values()]
    return dict(rows=rows,
                gx_range=[round(min(gx), 3), round(max(gx), 3)],
                alpha_range_eVA=[round(min(al), 3), round(max(al), 3)],
                runtime_s=round(time.time() - t0, 1))


def sec_C():
    """Seven-geometry bracket (fig10 g_bracket list), 6-band version."""
    t0 = time.time()
    rows = {}
    for name, (wy, wz, ezM) in GEOMS.items():
        res = extract6(ezM * 1e6, Wy=wy * 1e-9, Wz=wz * 1e-9,
                       ny=wy + 1, nz=wz + 1)
        rows[name] = _row(res)
        print(f"  C: {name} done t={time.time()-t0:.0f}s", flush=True)
    gx = [r["gx"] for r in rows.values()]
    return dict(rows=rows,
                gx_range=[round(min(gx), 3), round(max(gx), 3)],
                fourband_gx_range=[0.4, 1.07],
                measured_Geyer_gxx=[1.86, 2.31],
                runtime_s=round(time.time() - t0, 1))


def sec_D():
    """Delta_so sensitivity at the production point (Ez = 10 MV/m)."""
    t0 = time.time()
    rows = {}
    for dso in (44.0, 100.0, 300.0, 1e6):
        res = extract6(PROD["Ez"], Dso_meV=dso)
        rows[f"Dso{int(dso)}meV"] = _row(res)
        print(f"  D: Dso={dso:g} meV done t={time.time()-t0:.0f}s",
              flush=True)
    # 4-band references: lk_holes at its production FD grid (the paper's
    # fig10 numbers) and the Dso->inf dst row above (continuum 4-band limit)
    rows["fourband_lk_fd_11x13"] = _row(lk_holes.extract(PROD["Ez"]))
    return dict(rows=rows, runtime_s=round(time.time() - t0, 1))


SECS = {"A": sec_A, "B": sec_B, "C": sec_C, "D": sec_D}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sec", default="all", choices=list(SECS) + ["all"])
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    todo = list(SECS) if args.sec == "all" else [args.sec]
    ck = _load()
    for s in todo:
        if s in ck and not args.force:
            print(f"[{s}] cached, skipping (--force to redo)")
            continue
        if s != "A" and not ck.get("A", {}).get("all_passed"):
            print(f"[{s}] blocked: validation section A has not passed yet")
            continue
        print(f"[{s}] running...")
        ck[s] = SECS[s]()
        _save(ck)
        print(f"[{s}] " + json.dumps(ck[s], indent=1)[:2500])
    # ledger highlights
    led = {}
    if "A" in ck:
        led["validation_all_passed"] = ck["A"]["all_passed"]
        led["dso_inf_vs_4band_pct"] = ck["A"]["c_dso_inf_limit_fd"][
            "pct_diff"]
    if "B" in ck:
        led["gx_range_Ez_2_50"] = ck["B"]["gx_range"]
        led["alpha_range_eVA"] = ck["B"]["alpha_range_eVA"]
        led["table_10x12"] = ck["B"]["rows"]
    if "C" in ck:
        led["bracket_gx_range_6band"] = ck["C"]["gx_range"]
        led["bracket_gx_range_4band"] = ck["C"]["fourband_gx_range"]
        led["measured_Geyer_gxx"] = ck["C"]["measured_Geyer_gxx"]
    if "D" in ck:
        led["dso_sensitivity_prod"] = {k: dict(gx=v["gx"], gy=v["gy"],
                                               gz=v["gz"],
                                               alpha_eVA=v["alpha_eVA"],
                                               mstar=v["mstar"])
                                       for k, v in ck["D"]["rows"].items()}
    if led:
        save_numbers("kp6", led)


if __name__ == "__main__":
    main()
